apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: devx-mood
spec:
  source:
    git:
      url: https://github.com/dektlong/mood-sensors
      ref:
        branch: main
  serviceClaims:
    - name: rabbitmq-claim
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: reading
