---
swagger: "2.0"
info:
  description: "Swagger API definition for the mood-sensor component"
  version: "0.0.2"
  title: "Mood Sensors"
#basePath: "/v2"
tags:
- name: "activate"
  description: "Activate sensors"
- name: "measure"
  description: "Measure sensors data"
schemes:
- "https"
- "http"
paths:
  /activate/{sensorsID}:
    post:
      tags:
      - "activate"
      summary: "activate a sensor"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "ID of sensor to activate"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful sensor activation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid sensor activation"
  /activate:
    post:
      tags:
      - "activate"
      summary: "activate all available sensors"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful sensor activation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid sensor activation"
  /measure/{sensorsID}:
    get:
      tags:
      - "measure"
      summary: "Measure a mood status of a given sensors"
      produces:
      - "application/json"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "ID of sensor to measure"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
        400:
          description: "Invalid sensor data"
  /measure:
    get:
      tags:
      - "measure"
      summary: "Measure a mood status of all sensors"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
        400:
          description: "Invalid sensor data"