apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mood-sensors-apis
  description: APIs to interact with the mood-sensors component
spec:
  type: openapi
  lifecycle: development
  owner: hope-dev
  system: devx-mood
  definition:
   $text: https://github.com/Tembhum/mood-sensors/blob/dev/backstage/apis/mood-sensors-api-definition.yaml