apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mysensors
  description: Sensors backend api for the DevX Mood app
  tags:
    - spring-boot
    - spring-cloud-stream
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=mysensors'
spec:
  type: service
  lifecycle: development
  owner: dekt-dev-team2
  dependsOn: 
    - resource:reading
    - resource:mysensors-apis